"""Added on delete cascade to assignment and assignment statistics

Revision ID: 4861be3d3431
Revises: 9ce9e5733edc
Create Date: 2025-08-22 23:55:55.554591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4861be3d3431'
down_revision: Union[str, Sequence[str], None] = '9ce9e5733edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignment_statistics_assignment_id_fkey'), 'assignment_statistics', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_statistics', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('assignments_user_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'public_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_user_id_fkey'), 'assignments', 'public_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'assignment_statistics', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_statistics_assignment_id_fkey'), 'assignment_statistics', 'assignments', ['assignment_id'], ['id'])
    # ### end Alembic commands ###
