"""Updated assignment statistics model

Revision ID: 4c7b78d79c11
Revises: 6fa560939618
Create Date: 2025-08-28 12:16:54.915591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7b78d79c11'
down_revision: Union[str, Sequence[str], None] = '6fa560939618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_statistics', sa.Column('last_resumed_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assignment_statistics', sa.Column('remaining_seconds', sa.Integer(), nullable=True))
    op.drop_column('assignment_statistics', 'remaining_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_statistics', sa.Column('remaining_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('assignment_statistics', 'remaining_seconds')
    op.drop_column('assignment_statistics', 'last_resumed_time')
    # ### end Alembic commands ###
