"""Added last_paused_time and remaining_minutes field to enhance timer accuracy

Revision ID: 6fa560939618
Revises: 4861be3d3431
Create Date: 2025-08-28 10:02:32.508944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa560939618'
down_revision: Union[str, Sequence[str], None] = '4861be3d3431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_statistics', sa.Column('last_paused_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assignment_statistics', sa.Column('remaining_minutes', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_statistics', 'remaining_minutes')
    op.drop_column('assignment_statistics', 'last_paused_time')
    # ### end Alembic commands ###
