"""Updated AssignmentStatstic model. made elapsed time nullable and gave it a default value of 0

Revision ID: 9ce9e5733edc
Revises: 2deb0e37d2fd
Create Date: 2025-08-22 11:26:19.841835

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ce9e5733edc"
down_revision: Union[str, Sequence[str], None] = "2deb0e37d2fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assignment_statistics",
        "pause_count",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assignment_statistics",
        "pause_count",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
